# Configuração Unificada do Sistema de Percepção da RoboIME
# 
# Este arquivo contém todos os parâmetros de configuração para o sistema de percepção,
# incluindo configurações de câmera, detectores tradicionais e YOEO.

#=======================================#
# CONFIGURAÇÃO GERAL
#=======================================#

# Configuração do pipeline
pipeline:
  processing_fps: 120.0          # Taxa de processamento de imagens (FPS)
  debug_image: true             # Publicar imagens de debug
  
  # Habilitar/desabilitar sistemas
  use_yoeo: true                # Usar o detector YOEO
  use_traditional: true         # Usar os detectores tradicionais
  
  # Escolha de detector para cada tipo de objeto (opções: 'yoeo' ou 'traditional')
  detector_ball: "yoeo"         # Detector para a bola
  detector_field: "traditional" # Detector para o campo
  detector_lines: "traditional" # Detector para as linhas
  detector_goals: "yoeo"        # Detector para os gols
  detector_robots: "yoeo"       # Detector para os robôs

#=======================================#
# CONFIGURAÇÃO DA CÂMERA
#=======================================#
camera:
  # Tópicos ROS
  topic: "/camera/image_raw"    # Tópico da câmera para receber imagens
  info_topic: "/camera/camera_info"  # Tópico de informações da câmera
  
  # Configurações de imagem
  width: 1280                   # Resolução padrão (1280x720@120fps)
  height: 720
  fps: 120
  
  # Configurações específicas para IMX219
  camera_mode: 2                 # 0=3280x2464@21fps, 1=1920x1080@60fps, 2=1280x720@120fps
  exposure_time: 13333          # Tempo de exposição em microssegundos (otimizado para indoor)
  gain: 1.0                     # Ganho da câmera
  awb_mode: 1                   # Auto white balance
  brightness: 0                 # Brilho padrão
  saturation: 1.2              # Saturação aumentada para melhor detecção de cores
  enable_hdr: false            # HDR desabilitado por padrão
  enable_cuda: true            # Processamento CUDA habilitado
  enable_display: true        # Habilitar display
  display_fps: 15            # FPS reduzido para display remoto
  display_width: 640         # Resolução reduzida para display
  display_height: 360        # para melhor performance via SSH
  flip_method: 0              # Sem flip
  
  # Otimizações de processamento
  use_tensorrt: true          # Usar TensorRT para otimização
  enable_edge_enhancement: true # Aprimoramento de bordas
  enable_noise_reduction: true # Redução de ruído temporal
  enable_isp: true           # Image Signal Processing otimizado

#=======================================#
# CONFIGURAÇÃO DO YOEO
#=======================================#
yoeo:
  # Configurações do modelo
  model_path: "resources/models/yoeo_model.h5"  # Caminho para o modelo
  input_width: 416              # Largura da entrada do modelo
  input_height: 416             # Altura da entrada do modelo
  
  # Parâmetros de detecção
  confidence_threshold: 0.5     # Limiar de confiança para detecções
  iou_threshold: 0.45           # Limiar de IoU para NMS
  
  # Otimização
  use_tensorrt: true           # Usar TensorRT para otimização
  
  # Componentes habilitados
  components:
    ball: true                  # Habilitar detecção de bola
    field: false                 # Habilitar segmentação de campo
    lines: false                 # Habilitar segmentação de linhas
    goals: true                 # Habilitar detecção de gols
    robots: true                # Habilitar detecção de robôs
    referee: false              # Habilitar detecção de árbitro

#=======================================#
# CONFIGURAÇÃO DOS DETECTORES TRADICIONAIS
#=======================================#
traditional:
  # Detector de bola
  ball:
    enabled: false                      # Habilitar detector
    color_lower: [0, 120, 70]          # HSV mínimo (laranja)
    color_upper: [10, 255, 255]        # HSV máximo (laranja)
    min_radius: 10                     # Raio mínimo em pixels
    max_radius: 100                    # Raio máximo em pixels
    
  # Detector de campo
  field:
    enabled: true                      # Habilitar detector
    color_lower: [35, 40, 40]          # HSV mínimo (verde)
    color_upper: [85, 255, 255]        # HSV máximo (verde)
    morphology_kernel_size: 5          # Tamanho do kernel morfológico
    
  # Detector de linhas
  lines:
    enabled: true                     # Habilitar detector
    canny_threshold1: 50               # Limiar 1 para detector Canny
    canny_threshold2: 150              # Limiar 2 para detector Canny
    hough_rho: 1                       # Parâmetro rho para Hough
    hough_theta: 0.01                  # Parâmetro theta para Hough
    hough_threshold: 50                # Limiar para Hough
    
  # Detector de gols
  goals:
    enabled: false                     # Habilitar detector
    color_lower: [20, 0, 180]          # HSV mínimo (amarelo ou azul)
    color_upper: [30, 255, 255]        # HSV máximo (amarelo ou azul)
    min_height: 30                     # Altura mínima em pixels
    
  # Detector de robôs (obstáculos)
  robots:
    enabled: false                     # Habilitar detector
    color_lower: [0, 0, 0]             # HSV mínimo
    color_upper: [180, 255, 40]        # HSV máximo
    min_area: 100                      # Área mínima em pixels 

# Configurações de detecção
detection:
  # Configurações da bola
  ball:
    min_confidence: 0.6
    min_size: 10
    max_size: 100
    
  # Configurações do campo
  field:
    color_threshold: 40
    min_area: 1000
    
  # Configurações das linhas
  lines:
    canny_threshold1: 50
    canny_threshold2: 150
    min_line_length: 30
    
  # Configurações dos gols
  goals:
    min_confidence: 0.7
    min_height: 30
    
  # Configurações dos robôs
  robots:
    min_confidence: 0.6
    min_size: 20 