# Configuração para treinamento do modelo YOLOv4-Tiny
# Otimizado para detecção de objetos em futebol de robôs (apenas bounding boxes)

# Classes de detecção
classes: [
  'bola',    # Bola de futebol
  'gol',     # Postes de gol
  'robo'     # Robôs (próprios e adversários)
]

# Configurações do modelo
input_width: 416
input_height: 416
batch_size: 8
epochs: 100

# Diretórios dos datasets
data_dir: "C:/Users/Keller_/Desktop/RoboIME/HSL2025/src/perception/resources/dataset"
train_dir: "C:/Users/Keller_/Desktop/RoboIME/HSL2025/src/perception/resources/dataset/train"
val_dir: "C:/Users/Keller_/Desktop/RoboIME/HSL2025/src/perception/resources/dataset/valid"
test_dir: "C:/Users/Keller_/Desktop/RoboIME/HSL2025/src/perception/resources/dataset/test"

# Arquivos de anotações
train_annotations: "train/_annotations.coco.json"
val_annotations: "valid/_annotations.coco.json"
test_annotations: "test/_annotations.coco.json"

# Diretórios de saída
checkpoint_dir: "C:/Users/Keller_/Desktop/RoboIME/HSL2025/src/perception/resources/models/checkpoints"
log_dir: "C:/Users/Keller_/Desktop/RoboIME/HSL2025/src/perception/resources/models/logs"
output_dir: "C:/Users/Keller_/Desktop/RoboIME/HSL2025/src/perception/resources/models"

# Hiperparâmetros de treinamento
learning_rate: 0.001
warmup_epochs: 3
early_stopping_patience: 15

# Augmentação de dados
augmentation:
  rotation_range: 10
  width_shift_range: 0.1
  height_shift_range: 0.1
  brightness_range: [0.8, 1.2]
  horizontal_flip: true
  vertical_flip: false
  zoom_range: 0.1
  random_crop: false
  
# Opções de exportação
export_tensorrt: true
use_pretrained: true
pretrained_weights: null  # Será baixado automaticamente se use_pretrained=true

# Parâmetros de otimização
mixed_precision: true
workers: 8
use_multiprocessing: true

# Estrutura do dataset esperada:
# resources/dataset/
#   ├── train/
#   │   ├── img1.png
#   │   └── _annotations.coco.json     # Anotações COCO com bounding boxes
#   ├── valid/
#   │   ├── img2.png
#   │   └── _annotations.coco.json
#   └── test/
#       ├── img3.png
#       └── _annotations.coco.json 