path_planner_node:
  ros__parameters:
    field_length: 9.0
    field_width: 6.0
    planning_frequency: 5.0
    control_frequency: 20.0
    max_linear_velocity: 0.5
    max_angular_velocity: 1.2
    goal_tolerance: 0.2
    obstacle_radius: 0.3
    enable_visualization: true

navigation_manager_node:
  ros__parameters:
    enable_safety_checks: true
    localization_timeout: 5.0
    planning_timeout: 2.0
    navigation_timeout: 30.0
    min_localization_confidence: 0.3
    required_landmarks_for_navigation: 1

particle_filter_node:
  ros__parameters:
    field_length: 9.0
    field_width: 6.0
    num_particles: 500
    team_side: left
    publish_rate: 20.0
    enable_tf_broadcast: false
    resample_threshold: 0.5
    motion_noise_std: 0.05
    measurement_noise_std: 0.1

ekf_localization_node:
  ros__parameters:
    field_length: 9.0
    field_width: 6.0
    publish_rate: 20.0
    enable_tf_broadcast: false
    process_noise_std: 0.1
    measurement_noise_std: 0.15
    imu_noise_std: 0.02
    innovation_threshold: 9.0

navigation_coordinator_node:
  ros__parameters:
    field_length: 9.0
    field_width: 6.0
    robot_id: 1
    team_name: RoboIME
    team_side: left
    publish_rate: 20.0
    enable_tf_broadcast: true
    enable_team_communication: false
    confidence_threshold: 0.3
    use_global_localization: true