path_planner_node:
  ros__parameters:
    field_length: 9.0
    field_width: 6.0
    planning_frequency: 5.0
    control_frequency: 20.0
    max_linear_velocity: 0.5
    max_angular_velocity: 1.2
    goal_tolerance: 0.2
    obstacle_radius: 0.3
    enable_visualization: true

navigation_manager_node:
  ros__parameters:
    enable_safety_checks: true
    localization_timeout: 5.0
    planning_timeout: 2.0
    navigation_timeout: 30.0
    min_localization_confidence: 0.3
    required_landmarks_for_navigation: 1